declare module '*.svg'
declare module '*.png'
declare module '*.jpg'
declare module '*.jpeg'
declare module '*.gif'
declare module '*.bmp'
declare module '*.tiff'
declare module '*.less'
declare module "*.module.less";
declare module '*.sass'
declare module "*.module.sass";
declare module '*.scss'
declare module "*.module.scss";
declare module '*.css'
declare module "*.module.css";
